name: Testing - main

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          # windows-latest
        ]
        python-version: ["3.7", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install ase
        pip install -e .
    - name: pytest
      env:
        MPLBACKEND: "Agg"
      run: |
        cd tests
        pytest .
        cd ..
    # - name: Coveralls
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     coveralls --service=github
